apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"kubesphere.io/creator":"admin"},"labels":{"app":"shuwen-admin-ui"},"name":"shuwen-admin-ui","namespace":"shuwen"},"spec":{"ports":[{"name":"http-8000","port":8000,"protocol":"TCP","targetPort":8000}],"selector":{"app":"shuwen-admin-ui"},"sessionAffinity":"None","type":"ClusterIP"}}
    kubesphere.io/creator: admin
  creationTimestamp: '2022-04-21T00:22:52Z'
  labels:
    app: shuwen-admin-ui
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubesphere.io/creator': {}
          'f:labels':
            .: {}
            'f:app': {}
        'f:spec':
          'f:internalTrafficPolicy': {}
          'f:ipFamilyPolicy': {}
          'f:ports':
            .: {}
            'k:{"port":9527,"protocol":"TCP"}':
              .: {}
              'f:name': {}
              'f:port': {}
              'f:protocol': {}
              'f:targetPort': {}
          'f:sessionAffinity': {}
          'f:type': {}
      manager: kubectl-client-side-apply
      operation: Update
      time: '2022-04-21T00:22:52Z'
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
        'f:spec':
          'f:allocateLoadBalancerNodePorts': {}
          'f:externalTrafficPolicy': {}
          'f:selector': {}
          'f:type': {}
      manager: ACK-Console Apache-HttpClient
      operation: Update
      time: '2022-04-21T01:38:57Z'
  name: shuwen-admin-ui
  namespace: shuwen
  resourceVersion: '10697348'
  uid: d5ad40b4-12b7-4c23-9c9d-690b1e61b813
spec:
  clusterIP: 172.21.13.36
  clusterIPs:
    - 172.21.13.36
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http-9527
      port: 9527
      protocol: TCP
      targetPort: 9527
  selector:
    app: shuwen-admin-ui
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
