apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"kubesphere.io/creator":"admin"},"labels":{"app":"shuwen-admin"},"name":"shuwen-admin","namespace":"shuwen"},"spec":{"ports":[{"name":"http-8000","port":8000,"protocol":"TCP","targetPort":8000}],"selector":{"app":"shuwen-admin"},"sessionAffinity":"None","type":"ClusterIP"}}
    kubesphere.io/creator: admin
  creationTimestamp: '2022-04-08T11:13:28Z'
  labels:
    app: shuwen-admin
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
            'f:kubesphere.io/creator': {}
          'f:labels':
            .: {}
            'f:app': {}
        'f:spec':
          'f:internalTrafficPolicy': {}
          'f:ports':
            .: {}
            'k:{"port":8000,"protocol":"TCP"}':
              .: {}
              'f:name': {}
              'f:port': {}
              'f:protocol': {}
              'f:targetPort': {}
          'f:selector': {}
          'f:sessionAffinity': {}
      manager: kubectl-client-side-apply
      operation: Update
      time: '2022-04-08T11:13:28Z'
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:allocateLoadBalancerNodePorts': {}
          'f:externalTrafficPolicy': {}
          'f:type': {}
      manager: ACK-Console Apache-HttpClient
      operation: Update
      time: '2022-04-09T07:37:49Z'
  name: shuwen-admin
  namespace: shuwen
  resourceVersion: '4703481'
  uid: 8d6d5872-ac32-4f9a-acfe-829b4005a825
spec:
  clusterIP: 172.21.15.250
  clusterIPs:
    - 172.21.15.250
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http-8000
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: shuwen-admin
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
