apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"shuwen-service-api"},"name":"shuwen-service-api","namespace":"shuwen"},"spec":{"ports":[{"name":"http-8990","nodePort":30455,"port":8990,"protocol":"TCP","targetPort":8990}],"selector":{"app":"shuwen-service-api"},"sessionAffinity":"None","type":"NodePort"}}
  creationTimestamp: '2022-04-08T11:03:49Z'
  labels:
    app: shuwen-service-api
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
          'f:labels':
            .: {}
            'f:app': {}
        'f:spec':
          'f:externalTrafficPolicy': {}
          'f:internalTrafficPolicy': {}
          'f:ports':
            .: {}
            'k:{"port":8990,"protocol":"TCP"}':
              .: {}
              'f:name': {}
              'f:port': {}
              'f:protocol': {}
              'f:targetPort': {}
          'f:selector': {}
          'f:sessionAffinity': {}
      manager: kubectl-client-side-apply
      operation: Update
      time: '2022-04-08T11:03:49Z'
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:allocateLoadBalancerNodePorts': {}
          'f:type': {}
      manager: ACK-Console Apache-HttpClient
      operation: Update
      time: '2022-04-09T07:39:22Z'
  name: shuwen-service-api
  namespace: shuwen
  resourceVersion: '4703566'
  uid: 893f2d44-81d5-4611-ac5e-13aac11641f1
spec:
  clusterIP: 172.21.3.111
  clusterIPs:
    - 172.21.3.111
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http-8990
      port: 8990
      protocol: TCP
      targetPort: 8990
  selector:
    app: shuwen-service-api
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
